# Generated by Django 5.2.6 on 2025-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="view_count",
            field=models.PositiveIntegerField(verbose_name="Количество просмотров"),
        ),
    ]
