# Generated by Django 5.2.6 on 2025-10-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
