# Generated by Django 5.2.6 on 2025-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон для связи')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('main_office_address', models.CharField(max_length=200, verbose_name='Адрес офиса')),
                ('office_hours', models.CharField(max_length=200, verbose_name='Время работы офиса')),
                ('tg_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграмм')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ватсапп')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Инстаграмм')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
