# Generated by Django 5.2.6 on 2025-10-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_storecontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена за покупку"
            ),
        ),
    ]
