# Generated by Django 5.2.6 on 2025-10-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_purchase_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["purchase_price"],
                "permissions": [("can_unpublish_product", "Сan unpublish product")],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
