# Generated by Django 5.2.6 on 2025-10-30 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options_product_is_publish"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="catalog.category",
                verbose_name="Категория товара",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="storecontact",
            name="tg_contact",
            field=models.CharField(
                default="@tg_contact", max_length=50, verbose_name="Телеграмм"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="storecontact",
            name="whatsapp",
            field=models.CharField(
                default="8977-777-7777", max_length=50, verbose_name="Ватсапп"
            ),
            preserve_default=False,
        ),
    ]
